package com.example.midterm8911139.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3F5AA9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDCE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF00174A)
val md_theme_light_secondary = Color(0xFF575E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF141B2C)
val md_theme_light_tertiary = Color(0xFF745B85)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFDD6FF)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1236)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)

val md_theme_dark_primary = Color(0xFFB5C3FF)
val md_theme_dark_onPrimary = Color(0xFF0A2878)
val md_theme_dark_primaryContainer = Color(0xFF274090)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val md_theme_dark_secondary = Color(0xFFBFC6DC)
val md_theme_dark_onSecondary = Color(0xFF293042)
val md_theme_dark_secondaryContainer = Color(0xFF40475A)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE2F9)
val md_theme_dark_tertiary = Color(0xFFE2B9EE)
val md_theme_dark_onTertiary = Color(0xFF41274C)
val md_theme_dark_tertiaryContainer = Color(0xFF5A3F64)
val md_theme_dark_onTertiaryContainer = Color(0xFFFDD6FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E2E6)
